#!/usr/bin/env bash

# A shortcut to convert voice to code and pass it to an LLM with a system prompt.

set -euo pipefail

AUDIO="${XDG_CACHE_HOME:-$HOME/.cache}/talkcode/rec.opus"
mkdir -p "$(dirname "$AUDIO")"

echo "Recording… press Q to stop." >&2
# Mic only, 16 kHz mono, voice filtering, fast Opus
ffmpeg -hide_banner -v error \
  -f pulse -i default \
  -ac 1 -ar 16000 \
  -af "highpass=f=100,lowpass=f=6000" \
  -c:a libopus -b:a 16k -vbr on \
  -compression_level 2 -application voip -frame_duration 60 \
  -y "$AUDIO"

CMD="$@"
# Read system prompt from ./ask.md
if [[ -f ./ask.md ]]; then
  CMD="-s $(< ./ask.md) $CMD"
# If CMD is empty, use fzf to select a prompt
elif [[ -z "$CMD" ]]; then
  CMD="$(echo 'Transcribe. Drop fillers (um, uh...), correct minimally.
Answer with one-line fish code
Answer with one-line bash code' | FZF_DEFAULT_OPTS= fzf --print-query | tail -n1)"
fi

echo "$CMD" >&2

# Why Gemini not OpenAI? As of 11 Sep 2025: `llm` rejects -a with audio
llm -a "$AUDIO" -m gemini-2.5-flash "$CMD" \
  | tee /dev/tty \
  | {
      if [[ $CMD =~ [Cc]ode ]]; then
        # If CMD mentions "code", copy code block only
        awk 'BEGIN{f=0} /```/{f=!f; next} f{buf=buf $0 ORS} END{printf "%s", buf}'
      else
        # Copy everything
        cat
      fi
    } \
  | xclip -selection clipboard
