#!/usr/bin/env bash
# Speeds fzf search by caching files.
# Output is used by rofi-files.sh.
#
# $ update-files $dir   # Caches /mnt/$dir files into $HOME/.cache/sanand-scripts/files.$dir.txt
# $ update-files        # Caches $HOME     files into $HOME/.cache/sanand-scripts/files._home.txt
#                       # and all recent   files into $HOME/.cache/sanand-scripts/files.__recent.txt

set -euo pipefail

# Activate mise since we need fd which is mise-installed (~50ms)
eval "$(mise env -s bash)"

# Set up directories
TARGET="${1-}"  # empty => $HOME mode; non-empty => /mnt/$TARGET mode
OUTDIR="$HOME/.cache/sanand-scripts"
mkdir -p "$OUTDIR"
FD_WARNINGS="$OUTDIR/files.fd-warnings.log"
FIND_WARNINGS="$OUTDIR/files.find-warnings.log"

if [ -z "$TARGET" ]; then
    # No argument: search under $HOME
    OUT="$OUTDIR/files._home.txt"
    cd "$HOME"
    {
      fd --follow \
        --exclude node_modules \
        --exclude ImageCache \
        --exclude google-cloud-sdk \
        --exclude seek-ode-exam-programming-assignments-prod \
        2> "$FD_WARNINGS" || true
    } \
      | sponge "$OUT"
    # Cache files updated in the last week. Use find instead of fd to avoid an extra stat call
    {
      find "$HOME" \
        \( -name '.*' \
          -o -name node_modules \
          -o -name ImageCache \
          -o -name google-cloud-sdk \
          -o -path "$HOME/Downloads/seek-ode-exam-programming-assignments-prod" \) -prune -o \
        -type f -mtime -7 -printf '%T@ %P\0' \
        2> "$FIND_WARNINGS" || true
    } \
      | sort -z -nr \
      | awk -v RS='\0' '{ sub(/^[0-9.]+ /,""); print }' \
      | sponge "$OUTDIR/files.__recent.txt"
else
    # With argument: search under /mnt/$TARGET
    OUT="$OUTDIR/files.$TARGET.txt"
    cd /
    # If the target it mounted, i.e. non-empty, update
    if [ -d "/mnt/$TARGET" ] && find "/mnt/$TARGET" -mindepth 1 -print -quit | grep -q .; then
        fd -a . "/mnt/$TARGET" --follow | sponge "$OUT"
    fi
fi

# Sort. -u avoids duplicates
sort -u "$OUT" -o "$OUT"
